services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build: 
      context: .
      dockerfile: script/Dockerfile
    restart: "no"
    container_name: event_generator
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  grafana:
    image: grafana/grafana:11.6.15
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - db
      - app

volumes:
  postgres_data: