apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: events

resources:
  - grafana
  - postgres/postgres.yaml
  - script/event_generator.yaml

configMapGenerator:
  - name: init-sql
    files:
      - postgres/init.sql

secretGenerator:
  - name: db-secret
    envs:
      - .env
