{
 "title": "데이터 집계 시각화",
 "time": { "from": "2025-06-22T00:00:00.000Z", "to": "2026-06-21T00:00:00.000Z" },
 "panels": [
  {
   "title": "이벤트 타입별 발생 횟수",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "events",
     "rawSql": "select event_type, count(*) as cnt\r\nfrom events\r\ngroup by event_type\r\norder by cnt desc;"
    }
   ]
  },
  {
   "title": "시간대별 이벤트 추이",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "events",
     "rawSql": "select date_trunc('day', event_time) as daily, event_type, count(*) as cnt\r\nfrom events\r\ngroup by daily, event_type\r\norder by daily, event_type;"
    }
   ]
  },
  {
   "title": "전체 대비 에러 비율",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "events",
     "rawSql": "select \r\n\tROUND(100.0 * count(*) / (select count(*) from events), 2) as total_ratio\r\nfrom error;"
    }
   ]
  },
  {
   "title": "에러별 비율",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "events",
     "rawSql": "select \r\n\terror_code, \r\n\terror_msg,\r\n\tROUND(100.0 * count(*) / (select count(*) from events), 2) as ratio_per_error\r\nfrom error\r\ngroup by error_code, error_msg\r\norder by ratio_per_error desc;"
    }
   ]
  },
  {
   "title": "페이지뷰 TOP N",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "events",
     "rawSql": "select page_name, count(*) as cnt\r\nfrom events\r\nwhere event_type='page_view'\r\ngroup by page_name\r\norder by cnt desc\r\nlimit 10;"
    }
   ]
  }
 ]
}